Add Wallet Connect page
subvisual/discoveryDAO pull request #88
Opened 2022-04-12 18:18 UTC by flaviocastro

This PR adds the Wallet Connect page and all of it's states while the user is not connected to a wallet.

| Not Connected | Providers | Connecting | 
| ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/3527721/163026946-c374bb5d-5dc3-48c9-9a3c-724e6b4e3573.png) | ![image](https://user-images.githubusercontent.com/3527721/163027308-102190f8-f61e-4e46-8da5-0d021cd638d9.png) | ![image](https://user-images.githubusercontent.com/3527721/163027668-8fc74bd5-fb3f-4ad3-97f4-806961982125.png) |
| ![image](https://user-images.githubusercontent.com/3527721/163027183-cf246396-f863-4991-978a-0aec715fd4ab.png) | ![image](https://user-images.githubusercontent.com/3527721/163027358-5230cf71-fc29-4512-94d9-c715e9cd5230.png) | ![image](https://user-images.githubusercontent.com/3527721/163027606-a7ed568f-4e18-4de3-990d-50be05034d70.png) |
| ![image](https://user-images.githubusercontent.com/3527721/163027007-e6c8ff02-e137-4d58-915c-964734a29e8a.png) | ![image](https://user-images.githubusercontent.com/3527721/163027274-d90484f4-d434-45f7-8750-811f122f28d9.png) | ![image](https://user-images.githubusercontent.com/3527721/163027717-2a6d2d16-9631-4a02-9f29-03849ef1679c.png) |

2022-04-12 21:53 UTC, rafaelcruzazevedo requested changes

2022-04-12 21:53 UTC, rafaelcruzazevedo commented on packages/web/src/components/connect/hexagon-shape.tsx
> +export function HexagonShape(props: any) {
any?

2022-04-12 21:53 UTC, rafaelcruzazevedo commented on packages/web/src/components/screens/connect.tsx
> +    transform: none;
sort

2022-04-13 08:29 UTC, flaviocastro commented on packages/web/src/components/connect/hexagon-shape.tsx
> +export function HexagonShape(props: any) {
🔨

2022-04-13 13:52 UTC, rafaelcruzazevedo approved these changes

2022-04-13 13:53 UTC, merged